[project]
name = "upgrade-bep20"
authors = ["blockchain-innovations"]
description = "A secure BEP20 token upgrade and migration mechanism"
telemetry = false
requirements = []
[contracts.bep20-upgrade]
path = "contracts/bep20-upgrade.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
